services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: synkrypt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: synkrypt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    environment:
      DATABASE_URL: postgresql://synkrypt:password@db:5432/synkrypt
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  pgdata:
